services:
  mediawiki:
    image: synctree/mediawiki:1.24
    command: apache2-foreground
    health:
      type: normal
      endpoint: "/"
      protocol: http
      timeout: 180s
      accept:
      - '200'
      - 300-399
    ports:
    - 80:80:443
    volumes:
    - "/var/mediawiki/images:/var/www/html/images"
databases:
- mysql
