services:
  owncloud:
    image: l3iggs/owncloud
    ports:
    - 80:80:443
    volumes:
    - "/var/owncloud/data:/usr/share/webapps/owncloud/data:rw"
    - "/var/owncloud/config:/etc/webapps/owncloud/config:rw"
databases:
- mysql