---
services:
  gitlab:
    git_url: git://github.com/cloud66/apps-build
    git_branch: dev
    build_root: gitlab
    build_command: seeder.sh
    ports: 
    - '80:80:443'
    - container: 22
      tcp: 10022
    volumes:
    - "/var/gitlab/data:/var/opt/gitlab"
    - "/var/gitlab/logs:/var/log/gitlab"
    - "/var/gitlab/configurations:/etc/gitlab"
    health:
      type: inbound
      endpoint: "/users/sign_in"
      protocol: http
      timeout: 300s
      accept:
      - '200'
      - 300-399
databases:
- postgresql
- redis
