services:
  gitlab:
    image: sameersbn/gitlab:7.7.2
    ports:
    - 80:80:443
    health:
      type: normal
      endpoint: "/"
      protocol: http
      timeout: 600s
      accept:
      - '200'
      - 300-399
    volumes:
    - "/var/run/docker.sock:/run/docker.sock"
    - "/var/gitlab/data:/home/git/data"
    - "/var/gitlab/logs:/var/log/gitlab"
databases:
- mysql
- redis