---
services:
  ghost:
    image: cloud66/ghost:0.5.8
    ports:
    - 2368:80:443
    command: bash /ghost-start
    volumes:
    - "/var/ghost/data:/data"
    - "/var/ghost/ghost-override:/ghost-override"
    health:
      type: normal
      endpoint: "/"
      protocol: http
      timeout: 60s
      accept:
      - '200'
databases:
- mysql